<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/**  @var $block \Magento\Checkout\Block\Cart\Grid */

$isCheckedBox = $block->getLayout()->createBlock(\Kitchen\CustomExtraFee\Block\Index\Fee::class);
$quote = $isCheckedBox->getQuote();
?>
<?php $mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $block->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>" method="post" id="form-validate" data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "<?= $block->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
              "updateCartActionContainer": "#update_cart_action_container"}
          }' class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()) : ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar" data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <table id="shopping-cart-table" class="cart items data table" data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption class="table-caption"><?= $block->escapeHtml(__('Shopping Cart Items')) ?></caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?= $block->escapeHtml(__('Item')) ?></span></th>
                    <th class="col price" scope="col"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
                    <th class="col qty" scope="col"><span><?= $block->escapeHtml(__('Qty')) ?></span></th>
                    <th class="col subtotal" scope="col"><span><?= $block->escapeHtml(__('Subtotal')) ?></span></th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item) : ?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
        <?php if ($block->getPagerHtml()) : ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar" data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()) : ?>
            <a class="action continue" href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>" title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        <?php endif; ?>
        <?php if ($block->getViewModel()->isClearShoppingCartEnabled()) : ?>
            <button type="button" name="update_cart_action" data-cart-empty="" value="empty_cart" title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>" class="action clear" id="empty_cart_button">
                <span><?= $block->escapeHtml(__('Clear Shopping Cart')) ?></span>
            </button>
        <?php endif ?>
        <button type="submit" name="update_cart_action" data-cart-item-update="" value="update_qty" title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>" class="action update">
            <span><?= $block->escapeHtml(__('Update Shopping Cart')) ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update="" />
    </div>
    <?php 
        $asembly_option_for_customer = null;

        $isAsembly = $quote->getIsAsembly();
       
    ?>
    <div class="item-option-wrapper customer-option-wrapper">
        <div class="asembly-option">
            <input type="checkbox" class="checkbox" name="asembly_option_for_customer" id="asembly_option_for_customer" <?php if($isAsembly == 1){ echo 'checked';} ?> >
            <label class="label" for="asembly_option_for_customer"><?= $block->escapeHtml(__('Are You Want Assembly ?')) ?></label>
        </div>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>
<script type="text/javascript">
    require([
        "jquery", 
        "Magento_Ui/js/modal/confirm"
    ], function($, confirmation) {
        $('.customer-option-wrapper #asembly_option_for_customer').click(function() {
            var postData = {
                is_assembly_option_selected: $('#asembly_option_for_customer').is(':checked') ? 1 : 0
            };
            
            $.ajax({
                type: "POST",
                url: '<?= $block->getUrl('fee/index/fee') ?>',
                data: postData,
                showLoader: true,
                success: function(data) {
                    location.reload();                   
                },
                error: function(xhr, status, error) {
                    console.error('Error updating assembly option:', error);
                }
            });
        });
    });
</script>
